### ISSUE TITLE
Interest in using PyPI 'asimov' namespace?

### ISSUE THREAD

**Issue by matthewfeickert** [ligo-asimov/asimov#1]
@transientlunatic This isn't related to your JOSS review, but just a general question/curiosity. The package name is Asimov

https://github.com/ligo-asimov/asimov/blob/8201b27164f02954535c7edb65e1e116feb23b7a/setup.py#L28

but the installed / PyPI name is `ligo-asimov`

https://github.com/ligo-asimov/asimov/blob/8201b27164f02954535c7edb65e1e116feb23b7a/setup.py#L19

Is this (the use of `ligo-asimov`) only because [`asmiov` was already taken on PyPI](https://pypi.org/project/asimov/)? If so, I already pinged the author to see if they still use it at all for testing purposes (as there is only 1 sdist on there from 2018 to use as a placeholder) and they quickly responded that they 

> have no need for it anymore happy to transfer ownership

Would that be of interest to the Asimov team? If so, I'll ping them here and let the team and them get in contact.

I see though that [searching `ligo-` on PyPI](https://pypi.org/search/?q=ligo-&o=) turns up a large number of results, so maybe this is a recommended pattern by the LIGO/Virgo/KAGRA collaboration for all PyPI packages? If so, and the team has no interest in using the `asmiov` PyPI namespace that makes sense and please just feel free to close this Issue. :+1:

**Comment by transientlunatic** [comment]
Thanks @matthewfeickert! I'd definitely be keen to make use of that namespace; we mostly went with `ligo-asimov` because `asimov` isn't available on either pip or conda forge, but being able to run `pip install asimov` would be ideal even as a shim to `ligo-asimov`.
There used to be a loose convention within ligo that we prefixed packages `ligo-` but for various reasons we've generally started moving away from those.

**Comment by jbn** [comment]
Thanks for the ping, @matthewfeickert. I think the easiest way to affect a transfer is to have me invite @transientlunatic as a collaborator, then remove myself from the collaborators. If there is an easier way to do it, let me know. Otherwise, I need @transientlunatic's pypi username

**Comment by matthewfeickert** [comment]
> I think the easiest way to affect a transfer is to have me invite @transientlunatic as a collaborator, then remove myself from the collaborators.

This is what I've done in the past, so I think that's a good way to do it. PyPI also doesn't allow you to remove yourself if you're the sole owner of a project, so this is a safe way to ensure that a new owner has accepted permissions of a project before the old one steps away. :+1:

**Comment by jbn** [comment]
invited @transientlunatic on pypi

**Comment by transientlunatic** [comment]
Many thanks @jbn; it's very much appreciated! Apologies for taking a while to get back to you.

**Comment by jbn** [comment]
Happy to not-cybersquat for LIGO(-related) stuff. 

You folks are awesome!
