### ISSUE TITLE
[JOSS Review] Expand CI to cover all supported OS and Python versions

### ISSUE THREAD

**Issue by matthewfeickert** [ligo-asimov/asimov#2]
As I accidentally created a bit of a flurry of activity [on the review](https://github.com/openjournals/joss-reviews/issues/4170) about CI systems, I thought I'd open up this Issue so that we have a place to discuss things more usefully in the future.

Copying my comment from https://github.com/openjournals/joss-reviews/issues/4170#issuecomment-1047218826:

> In my mind, as long as you are testing the software on every OS and Python version that you **say that you support** this is sufficient testing. I haven't done my review yet, so maybe this is clear in the docs somewhere, but from the PyPI metadata classifiers
>
> https://github.com/ligo-asimov/asimov/blob/b64d9f804e9e4ce7056ba4899fe3c9fb46304e44/setup.py#L40-L48
>
> there is no OS information given, and while you're testing against Python 3.6 through Python 3.9
>
> https://github.com/ligo-asimov/asimov/blob/b64d9f804e9e4ce7056ba4899fe3c9fb46304e44/.gitlab-ci.yml#L8-L54
>
> (metadata should get updated to reflect this and what about Python 3.10?) there is no testing against macOS and Windows (do you support these OS, or only Linux?). Azure Pipelines is a good choice here in my experience if you're not already using GitHub Actions (probably not the easiest with a mirror from GitLab) and if you don't already have a workflow you like with CricleCI. I am not saying Appveyor is bad, just that I prefer Azure Pipelines and in my experience it is a nicer UX.

**Comment by transientlunatic** [comment]
Thanks @matthewfeickert I've added github actions to cover everything from python 3.6 to 3.10 on `ubuntu-latest`.
I'll confess I've never run github actions on macos or Windows, so it was useful to take the time to find out how to do that!

We don't officially support anything other than linux at the moment, so I should update the metadata to reflect that. Right now the code can't do anything without the `htcondor` package and its underlying library, which isn't available on macos.
However future plans are to make this an optional dependency, but it would need a fair amount of additional development.

**Comment by matthewfeickert** [comment]
> I've added github actions to cover everything from python 3.6 to 3.10 on `ubuntu-latest`.

:rocket: 

> I'll confess I've never run github actions on macos or Windows, so it was useful to take the time to find out how to do that!

It looks like you probably already figured that out from 

https://github.com/ligo-asimov/asimov/blob/0b4e59bbd88ccab642ff044208a55cdf7333d81b/.github/workflows/python-app.yml#L9-L16

but here it would just be

```yaml
         os: [ubuntu-latest, macos-latest]
```

> We don't officially support anything other than linux at the moment, so I should update the metadata to reflect that.

That's also totally fine (to only support Linux)! There's no requirement to support other things. It is just nice to test what you support.

> Right now the code can't do anything without the `htcondor` package and its underlying library, which isn't available on macos. However future plans are to make this an optional dependency, but it would need a fair amount of additional development.

Yeah that makes total sense/seems very reasonable. :+1: 

---

A thing I would suggest in general though, is to lean into having _multiple_ GitHub Action workflows that, like microservices, just do one thing (e.g. [`pyhf`'s workflows for an example](https://github.com/scikit-hep/pyhf/tree/1884c6c08bc5b629724dd9ef3c60ec4386353b94/.github/workflows))

If you have multiple workflows, like a test suite workflow, docs workflow, and lint workflow, then you can turn off the `fail-fast`

https://github.com/ligo-asimov/asimov/blob/0b4e59bbd88ccab642ff044208a55cdf7333d81b/.github/workflows/python-app.yml#L12-L13

and take advantage of the parallelism of GitHub Actions to run your full CI/CD much faster. You have good timing as [GitHub Actions just enabled partial re-runs](https://github.blog/2022-03-16-save-time-partial-re-runs-github-actions/) this week

This is a bit different in mentality to the approach that GitLab pipelines uses (to great success!) where all your CI/CD steps exist in a single file that you can then split out into multiple jobs.

I can appreciate that you might want to keep your CI/CD workflows based in GitLab Pipelines and if you need help on that I am happy to try to offer translation advice between the servies.

**Comment by transientlunatic** [comment]
Thanks @matthewfeickert.
I think this looks like sound advice for setting-up a more flexible approach to the CI/CD process.
Right now I think I will probably focus on keeping the main CI run on gitlab; all of our internal tooling and review processes in LIGO use this. However I expect that going ahead we will want to have a more robust approach on github for validating contributions which come from outside our collaboration.

I think `master` now has the updates you've requested to the CI configuration file however.
