### ISSUE TITLE
[JOSS Review] Clarify contributions of author list

### ISSUE THREAD

**Issue by matthewfeickert** [ligo-asimov/asimov#3]
For the JOSS general check of https://github.com/openjournals/joss-reviews/issues/4170

> **Contribution and authorship:** Has the submitting author (@transientlunatic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

Looking at [tag `v0.3.3` of the Asimov repo](https://git.ligo.org/asimov/asimov/-/tags/v0.3.3)

```console
$ git log --oneline ":(exclude)paper" | wc -l
382
$ git shortlog -s | cut -c8-
Avi Vajpeyi
Daniel Williams
Duncan Macleod
James Alexander Clark
Richard Philip Udall
Richard Udall
$ git log --author="Daniel Williams" --oneline ":(exclude)paper" | wc -l
373
```

As @transientlunatic has contributed nearly all of the code for the project it is unclear from the paper what the technical or intellectual contributions are of the other [authors listed on the paper](https://git.ligo.org/asimov/asimov/-/blob/a5ec0b327e20796bc544b4d9313c16187de3e0db/paper/paper.md#L7-28). This needs to be clarified (just here in this Issue is fine).

**Comment by transientlunatic** [comment]
Hi @matthewfeickert, am I okay to go ahead and close this issue now? If not please feel free to re-open.
